name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the release (e.g. v1.2.3)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to create tags

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Create tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

      - name: Install npm dependencies
        run: npm ci

      - name: Install composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Build assets
        run: npm run build

      - name: Generate i18n files
        run: composer run make-i18n

      - name: Package plugin
        run: npm run plugin-zip

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          draft: true
          files: fraktvalg.zip
